[build]
  command = "npm install && npm run build:functions" # Run npm install and then copy files
  publish = "." # The base directory for static assets.

[functions]
  directory = "functions" # Specifies the directory where Netlify should look for your functions

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
